spring:
  application:
    name: Cosmo-Cats-Intergalactic-Marketplace



application:
  currency:
    api:
      url: http://localhost:8089
  feature:
    toggles:
      cosmo-cats: true
      kitty-products: false
